.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" Copyright(c) 2001 by Arthur Korn <arthur@korn.ch>
.\" Copyright(c) 2001-2008 by wave++ "Yuri D'Elia" <wavexx@users.sf.net>
.\"
.\" Distributed under GNU GPL (v2 or above) WITHOUT ANY WARRANTY.
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WMND 1 "Jan 29, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
WMND \- WindowMaker network device monitor
.SH SYNOPSIS
.B wmnd
.RI "{ " options " }"
.SH DESCRIPTION
.B WMND
is a WindowMaker dock application that shows a graph of the network traffic
of the past few minutes, current activity and current and overall send
and receive rates. Additionally it can launch any program in response to
mouse clicks.
.SH OPTIONS
.TP
.BI "\-i " interface
Select the interface to start with.
.TP
.BI "\-I " interface
Interface/s to monitor. Defaults to all but lo and irda. Under linux
(using the linux_proc driver) you can specify multiple interfaces
separated by commas to force offline ones and combine them into
a single instance.
.TP
.BI "\-D " driver
Specify a driver to use. Defaults to auto-probe.
.TP
.B \-l
Start using long device names.
.TP
.B \-m
Start with maximal values hidden.
.TP
.B \-t
Start without displaying connection time of ppp links.
.TP
.B \-M
Use the maximal values of the entire history.
.TP
.BI "\-w " mode
Select display mode to start with.
Use
.B wmnd \-h
for a list of available display modes.
Right clicks on the graph cycle through all available modes.
.TP
.BI "\-r " rate
refresh rate in microseconds
.TP
.BI "\-s " scroll
scroll rate in tenths of seconds
.TP
.BI "\-S " steps
Number of scroll steps to wait before updating the speed rate indicator.
.TP
.B \-b
Scale the values of the maximum and current rate by factors of base 2 instead
of the default 10-based scaling. (1K equals 1024 in binary mode, but 1000
in decimal mode.)
.TP
.BI "\-c " color
tx color
.TP
.BI "\-C " color
rx color
.TP
.BI "\-L " color
middle line color
.TP
.BI "\-d " display
Draw onto X11 display \fIdisplay\fP
.TP
.BI "\-f " config
Read \fIconfig\fP instead of \fB~/.wmndrc\fP
.TP
.B \-F
Don't parse \fB~/.wmndrc\fP
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of \fBWMND\fP.
.TP
.B \-q
Be less verbose (display only errors).
.TP
.B \-Q
Show informational messages.
.TP
.BI "\-o " float
Smoothing factor (a float from 0 to 1).
.TP
.BI "\-a " bytes
Use a fixed scale for the bytes modes specified in bytes per second.
By default uses an automatic scale.
.TP
.BI "\-n " name
Change the \fBWMND\fP class/title name (defaults to "wmnd").

.SH USAGE
.SS Active Interface
You can cycle in realtime through all available active interfaces
by simply left-clicking on the interface name gadget on the
upperleft corner of \fBWMND\fP or use the mouse wheel.
.PP
The 'lo' interface is an exception, 'lo' only works when invoked
from the commandline (\fBwmnd \-I lo\fP), lo was mainly built in for
testing purposes.
.SS Device Name
By default, \fBWMND\fP show device name in short term of four characters,
for example, the ippp0 will be displayed as ipp0.  You can toggle
the device name between short and long by right-click on it.
.SS Graphic Mode
Left-click on the main graphic area to cycle the graphic mode.
.SS Max Meter
Left-click to toggle the history max or screen max, default is screen max when
\fBWMND\fP is startup. Right-click to hide or show.  Middle-click to zoom the
statistics in a separated \fBtrend\fP window. You can cycle the active
interface and middle-click again to monitor multiple interfaces concurrently.
.SS Byte/Packet Mode
Left-click on the letter gadgeted on the right-top corner can switch
between the Byte or Packet counter mode. "B" for byte, "p" for packet. The
current mode affects the external \fBtrend\fP window too.
.SS User Script
Click on the bottom rate meter can invoke the user command defined in
resource file .wmndrc.
.SS Dragging WMND
Be sure to drag \fBWMND\fP on it's outer edges, it's a bit picky due
to the large gfx pixmap it keeps. You can also use a
keyboard and mouse shortcut (perhaps ALT+left-click) in your window
manager to drag it around.
.SS Drivers
.TP
.B solaris_fpppd
Solaris/Linux ppp streams driver. Gathers device data from /dev/ppp. Uses code
from the Solaris/Linux pppd server and it should work wherever Solaris/Linux
pppd works.
.TP
.B linux_proc
Reads data from the linux
.BR proc (5)
virtual filesystem.
.TP
.B freebsd_sysctl
Uses the MIB to gather device statistics under FreeBSD (offline
devices handling is buggy, support needed!)
.TP
.B netbsd_ioctl
Read statistics through the NetBSD ioctl call.
.TP
.B solaris_kstat
Gathers device statistics through kstat counters. Uses libdladm for device
enumeration if available.
.TP
.B irix_pcp
Reads metrics from the IRIX Performance Co-Pilot daemon.
Interface format:

.RB [ host@ ] interface

.TP
.B generic_snmp
Query an IF-MIB capable snmp server for gathering interface
statistics. By default \fIgeneric_snmp\fP connects to localhost and
uses the public community. You can change the community/host/interface
to monitor by using the \fI\-I\fP flag:

.RB [ community @] host [: interface ]

You must specify an interface number, not an interface name. If the
interface number is 0, or there's no interface specification,
\fBWMND\fP will display all available interfaces. By default the
community name is "public". Beware that by specifying an snmp v1
community name on a command line can be dangerous on an multiuser
platform. Please read the README file on the distribution for more
details.
.TP
.B testing_dummy
This is the "last resort" driver, it shows a null device useful only
to make \fBWMND\fP don't exit when all other drivers failed. Can be
enhanced to display something at compile time.
.SH FILES
~/.wmndrc	User configuration.
.PP
The format of this file is described in the example file "wmndrc"
coming with the distribution (see \fI/usr/share/doc/wmnd/\fP).
.SH SIGNALS
.TP
.B SIGTERM SIGINT
Clean WMND shutdown.
.SH BUGS
Report bugs and suggestion to the current \fBWMND\fR maintainer:
wave++ <wavexx@users.sf.net>. More information (including usage
instructions) can be found into the README file found into the
distribution. These information should be integrated here too.
.SH SEE ALSO
.BR X (3x),
.BR wmaker (1x),
.BR proc (5),
.BR trend (1)
.SH AUTHOR
This manual page was written by Arthur Korn <arthur@korn.ch>.
The original \fBWMND\fR authour is Reed Lai, but it is currently
maintained by Yuri D'Elia <wavexx@users.sf.net>.
